version: '3.8'
services:
  mysql:
    image: mysql:5.7
    container_name: hotelbook_mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: hotelbook123123
      MYSQL_DATABASE: airbnb_db
      MYSQL_USER: hotelbook
      MYSQL_PASSWORD: hotelbook123123
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data: